### ISSUE TITLE
Mute Camera doesn't work

### ISSUE THREAD

**Issue by mdanetzky** [jjshoe/MuteDefaults#4] opened 2017-05-30 08:17 UTC
I have OSX Sierra, Chrome 58.0.3029.110 (64-bit).
When I start a call from Google Hangouts App the camera isn't muted despite of "Mute the camera automatically" being checked.

**Comment by blackwood** [comment] 2017-08-15 22:22
Ditto, doesn't change either camera or mic.

**Comment by abstratt** [comment] 2017-08-18 13:10
Same here, on Linux, Chrome 56.0.2924.87 (64-bit).

**Comment by abstratt** [comment] 2017-08-18 13:51
Duplicate of #1

**Comment by jjshoe** [comment] 2017-08-18 14:38
Closing as a duplicate of #1

**Closed as completed by jjshoe** 2017-08-18 14:38 UTC

**Comment by jjshoe** [comment] 2017-09-26 16:16
@mdanetzky @blackwood support for meets was just added, and rolled out today. Try version 2.0, and see if it works for you, if not, please open a new issue.
